#!/usr/bin/env bash
# Lets the contract tests link on a windows-gnu toolchain.
#
# Soroban contract crates are `crate-type = ["cdylib", "rlib"]`, which is what
# `stellar contract build` looks for. On windows-gnu, linking one of those
# cdylibs natively re-exports the whole Soroban host through a single DLL
# and lld gives up:
#
#     ld: error: export ordinal too large: 75749
#
# Nothing is wrong with the crates. The wasm build never hits this, because the
# wasm target links no DLL, and neither does any other platform. Only
# `cargo test` on Windows does, and only for a contract crate that another
# crate depends on.
#
# Two fixes, both local and both gitignored, written into `.cargo/config.toml`:
#
#   1. This workspace's own contracts link their native DLLs with no exports at
#      all. Nothing ever loads those DLLs; only the rlib beside them is used.
#      An empty export table keeps lld under its limit.
#   2. The OpenZeppelin crates come from crates.io and cannot be given a link
#      flag that way, so their published sources are copied out of the cargo
#      registry, the cdylib crate type dropped, and cargo pointed at the
#      copies. The project still depends on the published crates everywhere
#      else, at the versions the workspace pins.
#
# Run once after cloning, and again after changing an OpenZeppelin version.
#
#     bash scripts/windows-dev-setup.sh

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
registry="$(ls -d "${CARGO_HOME:-$HOME/.cargo}"/registry/src/*/ | head -1)"

crates=(
  "stellar-governance"
  "stellar-tokens"
  "stellar-access"
  "stellar-contract-utils"
)

mkdir -p "$root/vendor"
config="$root/.cargo/config.toml"
mkdir -p "$root/.cargo"
printf '# Generated by scripts/windows-dev-setup.sh. Not committed.\n[patch.crates-io]\n' > "$config"

patched=0
for crate in "${crates[@]}"; do
  src="$(ls -d "$registry$crate"-* 2>/dev/null | sort -V | tail -1 || true)"
  if [ -z "$src" ]; then
    echo "skipped $crate, not in the registry yet, run cargo fetch first"
    continue
  fi

  dest="$root/vendor/$crate"
  rm -rf "$dest"
  cp -r "$src" "$dest"
  chmod -R u+w "$dest"
  rm -f "$dest/.cargo-checksum.json"

  # Drop "cdylib" from the crate-type list, leaving the rlib behind.
  python - "$dest/Cargo.toml" <<'PY'
import re, sys
path = sys.argv[1]
text = open(path, encoding="utf8").read()
text = re.sub(r'crate-type = \[[^\]]*\]', 'crate-type = ["lib"]', text)
open(path, "w", encoding="utf8").write(text)
PY

  version="$(basename "$src" | sed "s/^$crate-//")"
  printf '%s = { path = "vendor/%s" }\n' "$crate" "$crate" >> "$config"
  echo "patched $crate $version"
  patched=$((patched + 1))
done

cat >> "$config" <<'CONFIG'

# Native DLLs for this workspace's contracts export nothing. Cargo links them
# only because the crates declare cdylib for the wasm build, and an empty
# export table is what keeps lld under its limit.
[target.x86_64-pc-windows-gnu]
rustflags = ["-C", "link-arg=-Wl,--exclude-all-symbols"]
CONFIG

echo
echo "$patched crate(s) patched, and native DLL exports turned off."
echo "cargo test should link now. stellar contract build never needed any of this."
